digitalocean/droplet-1-clicks

common/scripts/999-img_check.sh
After https://github.com/digitalocean/marketplace-partners/pull/142 was merged, img_check from this repo is outdated. This PR updates img_check bash script to support Rocky Linux and Centos Stream
=> [MP-3896] Add Rocky Linux and Centos Stream to supported OSs

lamp-18-04/files/var/www/html/index.html, lamp-20-04/files/var/www/html/index.html, lemp-18-04/files/var/www/html/index.html, lemp-20-04/files/var/www/html/index.html, mysql-20-04/files/var/www/html/index.html, wordpress-18-04/files/var/www/html/index.html, wordpress-20-04/files/var/www/html/index.html
Added button for ask question in `index.html` template
=> Updated index.html templates

common/scripts/900-cleanup.sh, django-22-04/template.json, dokku-20-04/template.json, nodejs-20-04/template.json
This PR adds support for $4 droplets to dokku and nodejs applications. Also there is a fix for a small issue with DO agent
=> Adding support for smallest droplet

django-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, lamp-18-04/scripts/011-lamp.sh, lamp-20-04/scripts/011-lamp.sh, wordpress-18-04/files/opt/digitalocean/wp_setup.sh, wordpress-20-04/files/opt/digitalocean/wp_setup.sh
DBaaS team changes the protocol line in dbaas configuration file, so our apps should be updated to support new format
=> Check dbaas protocol in applications

lemp-22-04/files/etc/nginx/sites-available/digitalocean, lemp-22-04/files/etc/update-motd.d/99-one-click, lemp-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, lemp-22-04/files/var/www/html/index.html, lemp-22-04/scripts/011-lemp.sh, lemp-22-04/template.json
Changed Ubuntu version to 22.04 and tested it.
=> Added Ubuntu 22.04 support to LEMP

django-22-04/files/etc/update-motd.d/99-one-click, django-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, django-22-04/scripts/012-django.sh
- Removed unnecessary code
- Fixed local database disable if dbaas detected
- Made motd dynamic based on dbaas/local database
Tested with local and managed db. All works!
Example of new readme if dbaas is selected
=> Fix Django readme

flask-22-04/files/etc/update-motd.d/99-one-click
Forgot to include this commit in initial Flask PR
=> Fixed motd

Makefile
fix URL to resolve to actual shell scripts
=> fix(make): resolve scripts

Makefile
=> Makefile mispelling in .PHONY

linuxgsm-20-04/files/etc/update-motd.d/99-one-click, linuxgsm-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot, linuxgsm-20-04/scripts/011-linuxgsm.sh, linuxgsm-20-04/template.json
I created game server for CS for test
=> MP-6270 LinuxGSM

supabase-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot
Looks like apt update can block supabase installation, so I updated the image
=> Fix supabase app

discourse-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, discourse-22-04/template.json
https://github.com/digitalocean/droplet-1-clicks/issues/134
=> Fix discourse setup process

elasticsearch-22-04/files/etc/update-motd.d/99-one-click, elasticsearch-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, elasticsearch-22-04/files/var/lib/digitalocean/elasticsearch.yml, elasticsearch-22-04/scripts/01-packages.sh, elasticsearch-22-04/template.json
This PR creates ElasticSearch 1-Click
ElasticSearch is configured with XPACK security and a randomly generated password. It is also configured in a single-node mode with a master node called `node-main`
Droplet is extremely easy to use, just spin it and use the ping command from Droplet MOTD to test it:
=> Create ElasticSearch 1-click

logstash-22-04/files/etc/update-motd.d/99-one-click, logstash-22-04/scripts/012-logstash.sh, logstash-22-04/template.json
A very simple packer script to just install LogStash.
LogStash cannot be partially configured, it's either a full configuration with inputs and outputs and data mapping or nothing. Hence, we cannot provide any sort of auto-configuration since we cannot ask people how they will process the data.
=> LogStash Droplet 1-Click

odoo-22-04/files/etc/project-configs/odoo16.conf, odoo-22-04/files/etc/project-configs/odoo16.service, odoo-22-04/files/etc/update-motd.d/99-one-click, odoo-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, odoo-22-04/scripts/012-odoo.sh, odoo-22-04/template.json
=> Odoo 1-click

mariadb-22-04/files/opt/digitalocean_mariadb/setup_mariadb.sh, mariadb-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, mariadb-22-04/scripts/010-mariadb.sh, mariadb-22-04/template.json
This PR adds required packer files for the new app - MariaDB
=> Create MariaDB droplet-1click app

ubuntu-desktop-22-04/files/opt/digitalocean_desktop/setup_vnc.sh, ubuntu-desktop-22-04/files/usr/lib/systemd/system/x11vnc.service, ubuntu-desktop-22-04/scripts/010-ubuntu-desktop.sh, ubuntu-desktop-22-04/template.json
This solution uses sddm and x11vnc. It works on droplets with 2G memory well.
=> Add Ubuntu Desktop 1click

gitlab-22-04/files/etc/update-motd.d/99-one-click, gitlab-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, gitlab-22-04/template.json
This PR upgrades the current Gitlab image by running it on Ubunutu 22.04 and adding an improved message of the day.
=> Add Gitlab-2204

airflow-22-04/files/etc/update-motd.d/99-one-click, airflow-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, airflow-22-04/template.json
After Airflow is published our team found couple of problems. This PR fixes them
=> Fix airflow 1click

bluesky-22-04/README.md, bluesky-22-04/files/root/bluesky_setup.sh, bluesky-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, bluesky-22-04/template.json
This PR adds BlueSky 1click application
=> Add bluesky 1click

hashicorp-vault-22-04/files/etc/systemd/system/vault.service, hashicorp-vault-22-04/scripts/012-vault.sh
This PR applies most of the recommendations mentioned there - https://developer.hashicorp.com/vault/tutorials/operations/production-hardening
=> Make HashiCorp Vault more secure

jupyter-conda-22-04/Catalog-README.md, jupyter-conda-22-04/README.md, jupyter-conda-22-04/config.pkr.hcl, jupyter-conda-22-04/files/etc/update-motd.d/99-one-click, jupyter-conda-22-04/files/root/Readme.txt, jupyter-conda-22-04/files/root/Save-9GB-by-deleting-examples.txt, jupyter-conda-22-04/files/root/jupyter/requirements.txt, jupyter-conda-22-04/files/root/notebook.sh, jupyter-conda-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot, jupyter-conda-22-04/marketplace-image.json, jupyter-conda-22-04/scripts/010-conda.sh, jupyter-conda-22-04/scripts/011-jupyter.sh
=> Jupyter 1-click

wordpress-22-04/files/root/wp_setup.sh, wordpress-22-04/template.json
This PR fixes dbaas protocol parsing for WordPress as well as fixes gpg key import for MySQL
TEST WITH DBAAS ✅ 
TEST WITHOUT DBAAS ✅
=> WordPressFixDbaas

django-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot
This PR fixes Django DBAAS integration 
Tested 🆗 
Logging in the admin console ✅ 
Migration are running correctly ✅
=> FixDjangoDbaas

lamp-24-04/files/etc/apache2/sites-available/000-default.conf, lamp-24-04/files/etc/update-motd.d/99-one-click, lamp-24-04/files/var/lib/cloud/scripts/per-instance/001_onboot, lamp-24-04/files/var/www/html/index.html, lamp-24-04/scripts/011-lamp.sh, lamp-24-04/template.json, lemp-24-04/files/etc/nginx/sites-available/digitalocean, lemp-24-04/files/etc/update-motd.d/99-one-click, lemp-24-04/files/var/lib/cloud/scripts/per-instance/001_onboot, lemp-24-04/files/var/www/html/index.html, lemp-24-04/scripts/011-lemp.sh, lemp-24-04/template.json
This PR updates LAMP & LEMP packer configuration files to use Ubuntu 24.04
=> Update lamp & lemp to Ubuntu 24.04

rabbitmq-24-04/files/etc/update-motd.d/99-one-click, rabbitmq-24-04/files/var/lib/cloud/scripts/per-instance/001_onboot, rabbitmq-24-04/scripts/011-rabbitmq.sh, rabbitmq-24-04/template.json
Changing ubuntu image version to `24-04-x64`
=> MP-7310 : rabbitmq-24-04

campfire-24-04/files/etc/update-motd.d/99-one-click, campfire-24-04/files/var/lib/cloud/scripts/per-instance/001_onboot, campfire-24-04/listing.md, campfire-24-04/scripts/campfire.sh, campfire-24-04/template.json
Adds the now open source Campfire from Basecamp to the marketplace.
=> Add campfire listing
