nodejs/files/etc/update-motd.d/99-one-click
nodejs/files/var/lib/cloud/scripts/per-instance/001_onboot
nodejs/files/var/www/html/hello.js
nodejs/scripts/011-packages.sh
nodejs/scripts/011-pm2.sh
nodejs/template.json

A user pointed out the PM2 runs Node as the user who invoked it. We don't want to run our web application as root. Update the Packer build for Node.js to run the web application as the nodejs user.

Run PM2 as the nodejs user

---

django-20-04/files/etc/update-motd.d/99-one-click
django-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot

We did not update our migration command after upgrading from Django 1.8
to Django 2.2. This PR fixes the migrations not being run and creates
the admin user.

Fix Django admin login

---

docker-18-04/files/var/lib/cloud/scripts/per-instance/001_onboot
docker-18-04/template.json
docker-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot
docker-20-04/template.json
dokku-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot
dokku-20-04/template.json

Fixes:
https://github.com/digitalocean/terraform-provider-digitalocean/issues/508
Some droplet 1-clicks don't need to configure the droplet before the user
can log in, and disabling ssh until cloud init finishes executing breaks
terraform for the docker 1-Clicks.

Remove unnecessary force ssh logout

---

discourse-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot
discourse-20-04/template.json
mysql-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot

Instead of configuring the firewall on boot, configure the firewall
when the image is being built using the existing ufw scripts.

Use ufw scripts for firewall

---

wordpress-20-04/files/opt/digitalocean/wp_setup.sh
wordpress-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot

Added support for dbaas credential injection during wp bootstrapping. I followed the pattern used by the boot.sh file used to start the image.

Mp 3164 add support for dbaas credentials

---

wordpress-20-04/files/opt/digitalocean/wp_setup.sh
wordpress-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot

See https://github.com/digitalocean/droplet-1-clicks/compare/tmp...wordpress for a diff between this branch and the wordpress image pre dbaas work.
Now, the script will wait for dbaas to be available before kicking off the setup process:

mp-3164 - add support for dbaas credentials (cont)

---

nodejs-20-04/files/etc/update-motd.d/99-one-click

updated message of the day to include mongo creds location and warning about cluster ready time
example with no creds present (notice the `On the server` section):
```
Welcome to Ubuntu 20.04 LTS (GNU/Linux 5.4.0-37-generic x86_64)
* Documentation:  https://help.ubuntu.com
* Management:     https://landscape.canonical.com
* Support:        https://ubuntu.com/advantage
System information as of Tue Jun 15 12:26:05 UTC 2021
System load:  0.0               Users logged in:       0
Usage of /:   4.7% of 48.29GB   IPv4 address for eth0: 159.89.184.236
Memory usage: 17%               IPv4 address for eth0: 10.17.0.7
Swap usage:   0%                IPv4 address for eth1: 10.108.0.4
Processes:    114
132 updates can be installed immediately.
0 of these updates are security updates.
To see these …
```

updated message of the day to include mongo goodness

---

lemp-18-04/files/etc/nginx/sites-available/digitalocean
lemp-18-04/template.json
lemp-20-04/files/etc/nginx/sites-available/digitalocean
lemp-20-04/template.json

This PR updates droplet-1-clicks installations for lemp: php8.0 will be installed with lemp 18-04 and lemp 20-04

Update php version to 8.0 in lemp

---

lamp-18-04/template.json
lamp-20-04/template.json

Update php version 7.4 -> 8.0 on ubuntu 20-04 and 18-04:

MP-3758: Update php version

---

wordpress-18-04/scripts/010-php.sh
wordpress-18-04/template.json
wordpress-20-04/scripts/010-php.sh
wordpress-20-04/template.json

Updates
- Wordpress-ubuntu-20-04:
mySQL: 7.4 -> 8.0
php: 7.4 -> 8.0
- Wordpress-ubuntu-18-04:
mySQL: 7.4 -> 8.0
php: 7.4 -> 8.0

MP-3489: update Wordpress tools

---

wordpress-18-04/template.json
wordpress-20-04/template.json

A customer found that wordpress works with errors, for example it's not possible to change themes in admin area. Also that customer found the solution - wordpress 5.8 doesn't have this problem
**What PR does**
Upgrade wordpress version to 5.8
**PR test results**

[MP-3976] Update wordpress version to 5.8

---

wordpress-18-04/files/etc/update-motd.d/99-one-click
wordpress-18-04/files/opt/digitalocean/wp_setup.sh
wordpress-20-04/files/etc/update-motd.d/99-one-click
wordpress-20-04/files/opt/digitalocean/wp_setup.sh

We are making updates within Marketplace->Predeploy to be more dynamic. Those changes make the
credentials written to file look slightly different. The changes in this PR will allow Wordpress/Dbaas to
continue to work, by looking for the updated variable names.

wordpress/{18-04,20-04}: update wp images to look for new predeploy variables

---

lamp-18-04/files/etc/update-motd.d/99-one-click
lamp-18-04/scripts/011-lamp.sh
lamp-20-04/files/etc/update-motd.d/99-one-click
lamp-20-04/scripts/011-lamp.sh

This set of changes should allow lamp to be used with
predeploy/dbaas. It will look for the credentials 
that predeploy writes to disk, and if they’re there
this means the user has requested a dbaas instance.
This will also ensure the local mysql instance on
the droplet is turned off, and it will also ping
the dbaas instance until it is ready.

droplet-1-clicks/lamp: update lamp to work with dbaas

---

nodejs-20-04/template.json

[MP-4703](https://jira.internal.digitalocean.com/browse/MP-4703)
In this PR updated version of NodeJS.
Before:
After:

MP-4703/Update NodeJS version

---

wordpress-18-04/template.json
wordpress-20-04/scripts/011-wordpress.sh
wordpress-20-04/template.json

After some updates (again), we found broken mysql installation in wordpress app. This PR fixes the problem (app is updated too)
**Screenshots***
How it was
After:

Fix mysql installation in wordpress app

---

nodejs-20-04/template.json

This PR updates NodeJS from version 16 to 18 in 1-click-droplet app
before:
after:
https://nodejs.org/en/about/releases/

Update nodejs version from 16 to 18

---

lamp-20-04/template.json

After checking the versions of all tools, it was revealed that only the PHP version needed to be updated, the new image has been checked and is awaiting approval on the vendor portal. 
Last versions of tools:
Apache
PHP
MySQL
Versions from new image:

Update LAMP version

---

wordpress-20-04/files/var/lib/cloud/scripts/per-instance/001_onboot

After receiving couple of report related to memory issues with wordpress on tiny droplets our team decided to turn off performance scheme in this case. This PR updates wordpress packer file to implement planned fix

Turn off performance scheme on tiny droplets for WordPress

---

django-22-04/scripts/012-django.sh

Nginx wasn't able to access the gunicorn socket due to the django user missing read permissions on the folder. This fixes that.

MP-5390: Update permissions for socket

---

jitsi-20-04/scripts/01-packages.sh

Our customer found that jitsi app doesn't work. This PR fixes the problem. `prosody` should be installed separately.

Fix jitsi app

---

phpmyadmin-22-04/template.json

Updated MyPHPAdmin Ubuntu version to 22.04
Also updated MyPHPAdmin from 5.0.3 to 5.2.0 because 5.0.3 was dropping a lot of `depricated` warnings.
Tested! Works good!

MyPHPAdmin Ubuntu 22.04 update

---

discourse-22-04/files/etc/update-motd.d/99-one-click
discourse-22-04/files/opt/digitalocean/setup_discourse.sh
discourse-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot
discourse-22-04/scripts/010-discourse.sh
discourse-22-04/template.json

Updated Discourse to run on Ubuntu 22.04
Tested! Works good:

Update Discourse to Ubuntu 22.04

---

wordpress-22-04/files/etc/apache2/conf-available/block-xmlrpc.conf
wordpress-22-04/files/etc/apache2/sites-available/000-default.conf
wordpress-22-04/files/etc/fail2ban/jail.d/wordpress-digitalocean.conf
wordpress-22-04/files/etc/update-motd.d/99-one-click
wordpress-22-04/files/root/wp_setup.sh
wordpress-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot
wordpress-22-04/files/var/www/html/index.html
wordpress-22-04/scripts/010-php.sh
wordpress-22-04/scripts/011-wordpress.sh
wordpress-22-04/scripts/012-apache.sh
wordpress-22-04/template.json

Updated WordPress to run on Ubuntu 22.04
WordPress updated from 6.0 to 6.1.1
Fail2Ban from 4.4.0.4 to 4.4.0.9

Update WordPress to Ubuntu 22.04

---

phpmyadmin-22-04/scripts/010-php-my-admin.sh
phpmyadmin-22-04/template.json

- Update phpMyAdmin 5.2.0 -> 5.2.1
- Created copy of phpMyAdmin setup scripts to separate `phpMyAdmin` from phpMyAdmin Droplet from `phpMyAdmin` from MySQL droplet
- As for now, phpMyAdmin droplet ships no configuration file at all. Decided to use sample configuration as main 
- Added blowfish secret generation
Before:
After:
Tested on remote DB. Works just fine!

Phpmyadmin Config Fix and Update

---

wordpress-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot

SnapShooter fails to run a backup for MySQL in WordPress droplet.
Apparently, a recent MySQL update introduced problems with the backup process:
https://github.com/mysql/mysql-server/commit/022e73ba6976b984658a1c2652178cd4b81aec28
This PR fixes the issue by providing `wordpress` MySQL user necessary privileges.
PR was tested, and both WordPress and SnapShooter work fine!
Tagging: @mrsimonbennett

Added sql privileges needed for SnapShooter

---

dokku-22-04/files/etc/update-motd.d/99-one-click
dokku-22-04/scripts/010-dokku.sh
dokku-22-04/template.json

- Updated Dokku OS Ubuntu 20.04 -> 22.04
- Updated Dokku app version  0.21.4 -> 0.30.6
- Updated Docker-Compose version 1.27.4 -> 2.18.1
Tested successfully :

Dokku Droplet 1-Click Update

---

supabase-22-04/files/etc/nginx/sites-available/supabase
supabase-22-04/files/var/lib/cloud/scripts/per-instance/001_onboot
supabase-22-04/files/var/supabase/supabase_ssl
supabase-22-04/scripts/011-supabase.sh

New supabase repo update broke our supabase app (https://github.com/supabase/supabase/commit/e974bcc02876b1706f31d37e28f41b6f3f22989e#diff-423deb13b7c401b1a7f41ee91c77f722e11d2f317d6a66b546524e8a04cc8b03L26). Also we had found other problem with supabase korn, it was failing cause of missed credentials in the configs (https://github.com/supabase/supabase/commit/b3114508d0043fa92b01068d9a0848b7e2115732).
This PR fixes both problems and turns off auto update for supabase docker compose files

Fix the supabase 1-click application

---

clickhouse-22-04/files/etc/clickhouse-server/users.d/default-password.xml
clickhouse-22-04/files/opt/digitalocean_clickhouse/setup_password.sh
clickhouse-22-04/scripts/010-clickhouse.sh
clickhouse-22-04/template.json

This PR adds the new 1click application packer files - Clickhouse. It's fully functional.
Note: server is started after `setup_password.sh`'s generated the new password for the current droplet

Add clickhouse app

---

django-22-04/template.json
flask-22-04/template.json

This PR updates packer scripts for Django and Flask to support $4 droplets. Also both applications are updated to the latest versions

Add $4 droplet support for django and flask

---

ubuntu-desktop-22-04/scripts/010-ubuntu-desktop.sh
ubuntu-desktop-22-04/template.json

This PR updates Ubuntu Desktop application with RDP server. So windows users will be able to use our application without additional installations

Add RDP server to Ubuntu Desktop

---

common/scripts/010-nodejs.sh
nodejs-20-04/template.json

Nodesource has moved from an apt source per distro/version to a setup script per version. Use the new method to install the latest stable version of NodeJS.

NodeJS: use updated install source for setup

---

common/scripts/011-docker-compose.sh
docker-22-04/template.json

If no docker compose version is provided, fetch the latest version. Also removes the version from the docker-22-04 template to allow autoupdate compatibility.

fetch latest version for docker-compose

---

lemp-24-04/template.json

Updated the paths in the template to use the correct file path

MP-7535 : LEMP Marketplace image creates with wrong OS

---

wordpress-22-04/files/root/wp_setup.sh

Our customers found that wordpress installation faults in AMS3 region. After successful reproduction our team started investigation why it's happening. Resolution was very strange - some of the wp processes run in background and install scripts should wait to avoid the problem. Probably, AMS3 is slow and it causes problems.
This PR adds sleeps in necessary places. Solution was tested

Fix wordpress install in AMS3 region

---

wordpress-22-04/scripts/010-php.sh
wordpress-22-04/scripts/011-wordpress.sh
wordpress-22-04/template.json

Makes the following updates to the 1-click:
- WP 6.8.1
- Auto update WP on install
- Update PHP to 8.3

Update wordpress and PHP

---

phpmyadmin-24-04/scripts/010-php-my-admin.sh

Issue : 
When creating a droplet from this image and accessing `http://<IP>/phpmyadmin`, the page throws a `Forbidden` error. Upon checking inside the droplet, the phpmyadmin package was present but not correctly installed (missing core files). The issue is resolved by reinstalling the package
RCA : 
Looks like during the upgrade to `Ubuntu 24.04`, the phpmyadmin package did not upgrade cleanly — its configuration remained, but its core application files were removed or not copied over due to package restructuring/dependency changes.
This left Apache/Nginx with a phpMyAdmin alias pointing to a path that no longer contained the required files, which resulted in a `403 Forbidden error`.
Reinstalling phpmyadmin restored the missing files and re-linked the configuration properly
Fix : 
- …

MP-7909 : Fix for Issue with PhpMyAdmin MarketPlace Image
